name: Trigger workflow with issue

on: [issues]
permissions:
  issues: write
jobs:
  start:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - run: echo "${{ secrets.FLAG1 }}" > flag
    - run: 'echo "${{ github.event.issue.body }}" > tmpfile'
